# Setup
title:               'Apian Loft'
tagline:             'by Jason Biatek'
description:         'Software development, creative projects, and explorations of how electrons can be arranged in interesting orders.'
url:                 https://biatek.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jason Biatek
  url:               https://github.com/jbiatek
  email:             jason@biatek.net

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
